#Analysis type: germline / somatic
analysis: somatic

#Analysis type: tumor-only (TO) / tumor-normal (TN) / normal-only (NO)
type: TO

#Sequencing type: pair-ended (PE) / single-read (SR)
seq_type: PE

#Enalble trimming: true / false
trim: "true"

#Technology type: illumina / iontorrent
tech: illumina

#Adapter sequence: If not using common adapters, specify here
adapter: "ATCACCGACTGCCCATAGAGAGGCTGAGAC"

#If seq_type == PE // Pair-end testing:
pe_samples:
  SRR35855706: #Sample name: fastq file path
    fastq1: "../data/fastq_files/SRR35855706_1.fastq"
    fastq2: "../data/fastq_files/SRR35855706_2.fastq"

#If seq_type == SR // Single-read testing
sr_samples: #Sample name: fastq file path
  IonXpress_040: "../data/fastq_files/IonXpress_040.fastq"

reference: hg38

hg38:
  genome: ../data/references/hg38.fa
  index: ../data/references/hg38.fa.bwt
  dict: ../data/references/hg38.dict
  fai: ../data/references/hg38.fa.fai